### ISSUE TITLE
Bugs in CSS include

### ISSUE THREAD

**Issue by lidia-d** [s-leger/lef_responsive_images#1]
Your include statement for CSS is "includeCss" yet for correct recognition by TYPO3 it should be "includeCSS", otherwise it will not be enbedded.
Also: you try to include the file "fixes.css", yet your file is named "fix.css"

**Comment by lidia-d** [comment]
Your <noscript> solution for the layoutKey bootstrappackage cannot quite work like that. Without propper CSS styling both image tags will appear (you get the loader.gif and the image).
I added a workaround to your CSS in my project (works also in IE):

html.no-js img {
	max-width: 100%;
}

html.no-js figure.image > img {
	visibility: hidden;
	display: none;
}

**Comment by s-leger** [comment]
Hi, thank you for reporting !

I'm woking hard on this plugin to provide some more advanced features like background css and alternative "no cookie" domain for images.
