### ISSUE TITLE
<noscript> workaround necessary

### ISSUE THREAD

**Issue by lidia-d** [s-leger/lef_responsive_images#2]
Your solution for the layoutKey bootstrappackage cannot quite work like that. Without propper CSS styling both image tags will appear (you get the loader.gif and the image).
I added a workaround to your CSS in my project (works also in IE):

html.no-js img {
max-width: 100%;
}

html.no-js figure.image > img {
visibility: hidden;
display: none;
}

**Comment by s-leger** [comment]
Hi,  
Sorry for this, i put my no-js settings somewhere else.
Note you should remove the direct child ">" selector in order for this to work when image has a link for lightbox. Removed selector class .image as with border it's .thumbnail. Set opacity and visibility for noscript img too.

html.no-js img.lazyload {
max-width: 100%;
}
html.no-js figure img.lazyload {
visibility: hidden;
display: none;
}
html.no-js figure noscript img.lazyload {
visibility: visible !important;
display: block;
max-width: 100%;
opacity: 1;
}
